// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package bmore is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	Activity
	Firewall
	Conversation
	HttpRequest
	KeyValue
	Chat
	Emoticon
*/
package bmore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Chat_Priority int32

const (
	// UNDEFINED = 0;
	Chat_LOW    Chat_Priority = 0
	Chat_MEDIUM Chat_Priority = 1
	Chat_HIGH   Chat_Priority = 2
)

var Chat_Priority_name = map[int32]string{
	0: "LOW",
	1: "MEDIUM",
	2: "HIGH",
}
var Chat_Priority_value = map[string]int32{
	"LOW":    0,
	"MEDIUM": 1,
	"HIGH":   2,
}

func (x Chat_Priority) String() string {
	return proto.EnumName(Chat_Priority_name, int32(x))
}
func (Chat_Priority) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type Chat_ContentType int32

const (
	// UNDEFINED = 0;
	Chat_TEXT     Chat_ContentType = 0
	Chat_HTML     Chat_ContentType = 1
	Chat_MARKDOWN Chat_ContentType = 2
)

var Chat_ContentType_name = map[int32]string{
	0: "TEXT",
	1: "HTML",
	2: "MARKDOWN",
}
var Chat_ContentType_value = map[string]int32{
	"TEXT":     0,
	"HTML":     1,
	"MARKDOWN": 2,
}

func (x Chat_ContentType) String() string {
	return proto.EnumName(Chat_ContentType_name, int32(x))
}
func (Chat_ContentType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 1} }

type Activity struct {
	SentAt        int64  `protobuf:"varint,1,opt,name=sent_at,json=sentAt" json:"sent_at,omitempty"`
	MessageNumber int32  `protobuf:"varint,2,opt,name=message_number,json=messageNumber" json:"message_number,omitempty"`
	Sender        string `protobuf:"bytes,3,opt,name=sender" json:"sender,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*Activity_Request
	//	*Activity_Chat
	Event isActivity_Event `protobuf_oneof:"event"`
}

func (m *Activity) Reset()                    { *m = Activity{} }
func (m *Activity) String() string            { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()               {}
func (*Activity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isActivity_Event interface {
	isActivity_Event()
}

type Activity_Request struct {
	Request *HttpRequest `protobuf:"bytes,4,opt,name=request,oneof"`
}
type Activity_Chat struct {
	Chat *Chat `protobuf:"bytes,5,opt,name=chat,oneof"`
}

func (*Activity_Request) isActivity_Event() {}
func (*Activity_Chat) isActivity_Event()    {}

func (m *Activity) GetEvent() isActivity_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Activity) GetSentAt() int64 {
	if m != nil {
		return m.SentAt
	}
	return 0
}

func (m *Activity) GetMessageNumber() int32 {
	if m != nil {
		return m.MessageNumber
	}
	return 0
}

func (m *Activity) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Activity) GetRequest() *HttpRequest {
	if x, ok := m.GetEvent().(*Activity_Request); ok {
		return x.Request
	}
	return nil
}

func (m *Activity) GetChat() *Chat {
	if x, ok := m.GetEvent().(*Activity_Chat); ok {
		return x.Chat
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Activity) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Activity_OneofMarshaler, _Activity_OneofUnmarshaler, _Activity_OneofSizer, []interface{}{
		(*Activity_Request)(nil),
		(*Activity_Chat)(nil),
	}
}

func _Activity_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Activity)
	// event
	switch x := m.Event.(type) {
	case *Activity_Request:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Request); err != nil {
			return err
		}
	case *Activity_Chat:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Chat); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Activity.Event has unexpected type %T", x)
	}
	return nil
}

func _Activity_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Activity)
	switch tag {
	case 4: // event.request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HttpRequest)
		err := b.DecodeMessage(msg)
		m.Event = &Activity_Request{msg}
		return true, err
	case 5: // event.chat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Chat)
		err := b.DecodeMessage(msg)
		m.Event = &Activity_Chat{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Activity_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Activity)
	// event
	switch x := m.Event.(type) {
	case *Activity_Request:
		s := proto.Size(x.Request)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Activity_Chat:
		s := proto.Size(x.Chat)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Firewall struct {
	BlockIt bool `protobuf:"varint,1,opt,name=block_it,json=blockIt" json:"block_it,omitempty"`
}

func (m *Firewall) Reset()                    { *m = Firewall{} }
func (m *Firewall) String() string            { return proto.CompactTextString(m) }
func (*Firewall) ProtoMessage()               {}
func (*Firewall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Firewall) GetBlockIt() bool {
	if m != nil {
		return m.BlockIt
	}
	return false
}

type Conversation struct {
	SentAt int64   `protobuf:"varint,1,opt,name=sent_at,json=sentAt" json:"sent_at,omitempty"`
	Chats  []*Chat `protobuf:"bytes,2,rep,name=chats" json:"chats,omitempty"`
}

func (m *Conversation) Reset()                    { *m = Conversation{} }
func (m *Conversation) String() string            { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()               {}
func (*Conversation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Conversation) GetSentAt() int64 {
	if m != nil {
		return m.SentAt
	}
	return 0
}

func (m *Conversation) GetChats() []*Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

type HttpRequest struct {
	Ip            string               `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	RequestMethod string               `protobuf:"bytes,4,opt,name=request_method,json=requestMethod" json:"request_method,omitempty"`
	Host          string               `protobuf:"bytes,5,opt,name=host" json:"host,omitempty"`
	Port          int32                `protobuf:"varint,6,opt,name=port" json:"port,omitempty"`
	Script        string               `protobuf:"bytes,7,opt,name=script" json:"script,omitempty"`
	Path          string               `protobuf:"bytes,8,opt,name=path" json:"path,omitempty"`
	Parameters    map[string]*KeyValue `protobuf:"bytes,9,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]*KeyValue `protobuf:"bytes,10,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HttpRequest) Reset()                    { *m = HttpRequest{} }
func (m *HttpRequest) String() string            { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()               {}
func (*HttpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HttpRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *HttpRequest) GetRequestMethod() string {
	if m != nil {
		return m.RequestMethod
	}
	return ""
}

func (m *HttpRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HttpRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *HttpRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *HttpRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HttpRequest) GetParameters() map[string]*KeyValue {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *HttpRequest) GetHeaders() map[string]*KeyValue {
	if m != nil {
		return m.Headers
	}
	return nil
}

type KeyValue struct {
	Key   string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Chat struct {
	Sender      string           `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Receiver    string           `protobuf:"bytes,2,opt,name=receiver" json:"receiver,omitempty"`
	Text        string           `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Count       uint32           `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	Priority    Chat_Priority    `protobuf:"varint,5,opt,name=priority,enum=bmore.Chat_Priority" json:"priority,omitempty"`
	ContentType Chat_ContentType `protobuf:"varint,6,opt,name=content_type,json=contentType,enum=bmore.Chat_ContentType" json:"content_type,omitempty"`
	Emoticon    *Emoticon        `protobuf:"bytes,7,opt,name=emoticon" json:"emoticon,omitempty"`
	Tags        []string         `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty"`
}

func (m *Chat) Reset()                    { *m = Chat{} }
func (m *Chat) String() string            { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()               {}
func (*Chat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Chat) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Chat) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Chat) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Chat) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Chat) GetPriority() Chat_Priority {
	if m != nil {
		return m.Priority
	}
	return Chat_LOW
}

func (m *Chat) GetContentType() Chat_ContentType {
	if m != nil {
		return m.ContentType
	}
	return Chat_TEXT
}

func (m *Chat) GetEmoticon() *Emoticon {
	if m != nil {
		return m.Emoticon
	}
	return nil
}

func (m *Chat) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Emoticon struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Emoticon) Reset()                    { *m = Emoticon{} }
func (m *Emoticon) String() string            { return proto.CompactTextString(m) }
func (*Emoticon) ProtoMessage()               {}
func (*Emoticon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Emoticon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Activity)(nil), "bmore.Activity")
	proto.RegisterType((*Firewall)(nil), "bmore.Firewall")
	proto.RegisterType((*Conversation)(nil), "bmore.Conversation")
	proto.RegisterType((*HttpRequest)(nil), "bmore.HttpRequest")
	proto.RegisterType((*KeyValue)(nil), "bmore.KeyValue")
	proto.RegisterType((*Chat)(nil), "bmore.Chat")
	proto.RegisterType((*Emoticon)(nil), "bmore.Emoticon")
	proto.RegisterEnum("bmore.Chat_Priority", Chat_Priority_name, Chat_Priority_value)
	proto.RegisterEnum("bmore.Chat_ContentType", Chat_ContentType_name, Chat_ContentType_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x9d, 0xaf, 0xf5, 0x24, 0x4d, 0xad, 0x55, 0x45, 0x4d, 0x0f, 0x90, 0x5a, 0xaa, 0x14,
	0x84, 0x14, 0x50, 0xb8, 0x40, 0x6f, 0xfd, 0x08, 0xa4, 0xb4, 0x69, 0xab, 0x55, 0xa0, 0xdc, 0x22,
	0xc7, 0x5d, 0x35, 0x56, 0x63, 0xaf, 0x59, 0x6f, 0x02, 0xfe, 0x5f, 0x9c, 0xf9, 0x4b, 0xfc, 0x05,
	0xb4, 0xe3, 0x4d, 0x6a, 0x4a, 0x39, 0x71, 0x9b, 0x8f, 0x37, 0x33, 0xfb, 0x5e, 0x9e, 0x03, 0xed,
	0x98, 0x67, 0x59, 0x70, 0xcb, 0xb3, 0x5e, 0x2a, 0x85, 0x12, 0xb4, 0x36, 0x8d, 0x85, 0xe4, 0xfe,
	0x4f, 0x0b, 0xc8, 0x61, 0xa8, 0xa2, 0x65, 0xa4, 0x72, 0xba, 0x03, 0x8d, 0x8c, 0x27, 0x6a, 0x12,
	0x28, 0xcf, 0xea, 0x58, 0xdd, 0x0a, 0xab, 0xeb, 0xf4, 0x50, 0xd1, 0xfd, 0xf5, 0xf8, 0x24, 0x59,
	0xc4, 0x53, 0x2e, 0x3d, 0xbb, 0x63, 0x75, 0x6b, 0x6c, 0xd3, 0x54, 0x2f, 0xb0, 0x48, 0x9f, 0x80,
	0x1e, 0xb8, 0xe1, 0xd2, 0xab, 0x74, 0xac, 0xae, 0xc3, 0x4c, 0x46, 0x7b, 0xd0, 0x90, 0xfc, 0xeb,
	0x82, 0x67, 0xca, 0xab, 0x76, 0xac, 0x6e, 0xb3, 0x4f, 0x7b, 0x78, 0xbd, 0x37, 0x54, 0x2a, 0x65,
	0x45, 0x67, 0xb8, 0xc1, 0x56, 0x20, 0xba, 0x07, 0xd5, 0x70, 0x16, 0x28, 0xaf, 0x86, 0xe0, 0xa6,
	0x01, 0x1f, 0xcf, 0x02, 0x8d, 0xc2, 0xd6, 0x51, 0x03, 0x6a, 0x7c, 0xc9, 0x13, 0xe5, 0xef, 0x03,
	0x79, 0x1f, 0x49, 0xfe, 0x2d, 0x98, 0xcf, 0xe9, 0x53, 0x20, 0xd3, 0xb9, 0x08, 0xef, 0x26, 0x51,
	0x41, 0x80, 0xb0, 0x06, 0xe6, 0xa7, 0xca, 0xff, 0x08, 0xad, 0x63, 0x91, 0x2c, 0xb9, 0xcc, 0x02,
	0x15, 0x89, 0xe4, 0xdf, 0x54, 0xf7, 0xa0, 0xa6, 0x0f, 0x64, 0x9e, 0xdd, 0xa9, 0x3c, 0x38, 0xce,
	0x8a, 0x8e, 0xff, 0xa3, 0x02, 0xcd, 0xd2, 0xcb, 0x69, 0x1b, 0xec, 0x28, 0x35, 0x94, 0xed, 0x28,
	0xd5, 0x6a, 0x19, 0x26, 0x93, 0x98, 0xab, 0x99, 0xb8, 0x41, 0xd6, 0x0e, 0xdb, 0x34, 0xd5, 0x11,
	0x16, 0x29, 0x85, 0xea, 0x4c, 0x64, 0x05, 0x4b, 0x87, 0x61, 0xac, 0x6b, 0xa9, 0x90, 0xca, 0xab,
	0xa3, 0xbc, 0x18, 0xa3, 0xaa, 0xa1, 0x8c, 0x52, 0xe5, 0x35, 0x8c, 0xaa, 0x98, 0x21, 0x36, 0x50,
	0x33, 0x8f, 0x14, 0xf3, 0x3a, 0xa6, 0x47, 0x00, 0x69, 0x20, 0x83, 0x98, 0x2b, 0x2e, 0x33, 0xcf,
	0x41, 0x0a, 0xfe, 0xdf, 0x62, 0xf7, 0xae, 0xd6, 0xa0, 0x41, 0xa2, 0x64, 0xce, 0x4a, 0x53, 0xf4,
	0x1d, 0x34, 0x66, 0x3c, 0xb8, 0xd1, 0x0b, 0x00, 0x17, 0x3c, 0x7f, 0x64, 0xc1, 0xb0, 0x40, 0x14,
	0xd3, 0x2b, 0xfc, 0xee, 0x05, 0x6c, 0x3d, 0xd8, 0x4c, 0x5d, 0xa8, 0xdc, 0xf1, 0x1c, 0x45, 0x76,
	0x98, 0x0e, 0xe9, 0x3e, 0xd4, 0x96, 0xc1, 0x7c, 0xc1, 0xd1, 0x43, 0xcd, 0xfe, 0x96, 0xd9, 0x7e,
	0xc6, 0xf3, 0xcf, 0xba, 0xcc, 0x8a, 0xee, 0x81, 0xfd, 0xd6, 0xda, 0x3d, 0x83, 0x56, 0xf9, 0xd0,
	0x7f, 0x2d, 0xf3, 0xfb, 0x40, 0x56, 0xe5, 0x47, 0x16, 0x6d, 0xdf, 0x2f, 0xaa, 0x74, 0x1d, 0x33,
	0xe7, 0xff, 0xb2, 0xa1, 0xaa, 0x7f, 0xfa, 0x92, 0xb5, 0xad, 0x3f, 0xac, 0xbd, 0x0b, 0x44, 0xf2,
	0x90, 0x47, 0x4b, 0xf3, 0x4d, 0x38, 0x6c, 0x9d, 0xeb, 0x1f, 0x48, 0xf1, 0xef, 0xca, 0x38, 0x03,
	0x63, 0x7d, 0x26, 0x14, 0x8b, 0xa4, 0xf8, 0x10, 0x36, 0x59, 0x91, 0xd0, 0xd7, 0x40, 0x52, 0x19,
	0x09, 0x19, 0xa9, 0x1c, 0xed, 0xd0, 0xee, 0x6f, 0x97, 0x7c, 0xd7, 0xbb, 0x32, 0x3d, 0xb6, 0x46,
	0xd1, 0x03, 0x68, 0x85, 0x22, 0x51, 0xda, 0xc2, 0x2a, 0x4f, 0x39, 0x1a, 0xa6, 0xdd, 0xdf, 0x29,
	0x4f, 0x1d, 0x17, 0xfd, 0x71, 0x9e, 0x72, 0xd6, 0x0c, 0xef, 0x13, 0xfa, 0x12, 0x08, 0x8f, 0x85,
	0x8a, 0x42, 0x91, 0xa0, 0xa5, 0xee, 0x65, 0x1b, 0x98, 0x32, 0x5b, 0x03, 0x90, 0x44, 0x70, 0x9b,
	0x79, 0x04, 0x65, 0xc1, 0xd8, 0x7f, 0x01, 0x64, 0xf5, 0x24, 0xda, 0x80, 0xca, 0xf9, 0xe5, 0xb5,
	0xbb, 0x41, 0x01, 0xea, 0xa3, 0xc1, 0xc9, 0xe9, 0xa7, 0x91, 0x6b, 0x51, 0x02, 0xd5, 0xe1, 0xe9,
	0x87, 0xa1, 0x6b, 0xfb, 0xaf, 0xa0, 0x59, 0x7a, 0x87, 0x6e, 0x8c, 0x07, 0x5f, 0xc6, 0xee, 0x06,
	0x42, 0xc6, 0xa3, 0x73, 0xd7, 0xa2, 0x2d, 0x20, 0xa3, 0x43, 0x76, 0x76, 0x72, 0x79, 0x7d, 0xe1,
	0xda, 0xfe, 0x33, 0x20, 0x83, 0xd2, 0xed, 0x24, 0x88, 0xb9, 0x91, 0x1c, 0xe3, 0x69, 0x1d, 0xff,
	0xbe, 0xde, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x4e, 0x57, 0x93, 0xd0, 0x04, 0x00, 0x00,
}
