# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bmore.Activity" do
    optional :sent_at, :int64, 1
    optional :message_number, :int32, 2
    optional :sender, :string, 3
    oneof :event do
      optional :request, :message, 4, "bmore.HttpRequest"
      optional :chat, :message, 5, "bmore.Chat"
    end
  end
  add_message "bmore.Firewall" do
    optional :block_it, :bool, 1
  end
  add_message "bmore.Conversation" do
    optional :sent_at, :int64, 1
    repeated :chats, :message, 2, "bmore.Chat"
  end
  add_message "bmore.HttpRequest" do
    optional :ip, :string, 3
    optional :request_method, :string, 4
    optional :host, :string, 5
    optional :port, :int32, 6
    optional :script, :string, 7
    optional :path, :string, 8
    map :parameters, :string, :message, 9, "bmore.KeyValue"
    map :headers, :string, :message, 10, "bmore.KeyValue"
  end
  add_message "bmore.KeyValue" do
    optional :key, :string, 1
    repeated :value, :string, 2
  end
  add_message "bmore.Chat" do
    optional :sender, :string, 1
    optional :receiver, :string, 2
    optional :text, :string, 3
    optional :count, :uint32, 4
    optional :priority, :enum, 5, "bmore.Chat.Priority"
    optional :content_type, :enum, 6, "bmore.Chat.ContentType"
    optional :emoticon, :message, 7, "bmore.Emoticon"
    repeated :tags, :string, 8
  end
  add_enum "bmore.Chat.Priority" do
    value :LOW, 0
    value :MEDIUM, 1
    value :HIGH, 2
  end
  add_enum "bmore.Chat.ContentType" do
    value :TEXT, 0
    value :HTML, 1
    value :MARKDOWN, 2
  end
  add_message "bmore.Emoticon" do
    optional :name, :string, 1
  end
end

module Bmore
  Activity = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.Activity").msgclass
  Firewall = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.Firewall").msgclass
  Conversation = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.Conversation").msgclass
  HttpRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.HttpRequest").msgclass
  KeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.KeyValue").msgclass
  Chat = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.Chat").msgclass
  Chat::Priority = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.Chat.Priority").enummodule
  Chat::ContentType = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.Chat.ContentType").enummodule
  Emoticon = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmore.Emoticon").msgclass
end
