/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.bmore.Chat');
goog.provide('proto.bmore.Chat.ContentType');
goog.provide('proto.bmore.Chat.Priority');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.bmore.Emoticon');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bmore.Chat = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bmore.Chat.repeatedFields_, null);
};
goog.inherits(proto.bmore.Chat, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bmore.Chat.displayName = 'proto.bmore.Chat';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bmore.Chat.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bmore.Chat.prototype.toObject = function(opt_includeInstance) {
  return proto.bmore.Chat.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bmore.Chat} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bmore.Chat.toObject = function(includeInstance, msg) {
  var f, obj = {
    sender: jspb.Message.getFieldWithDefault(msg, 1, ""),
    receiver: jspb.Message.getFieldWithDefault(msg, 2, ""),
    text: jspb.Message.getFieldWithDefault(msg, 3, ""),
    count: jspb.Message.getFieldWithDefault(msg, 4, 0),
    priority: jspb.Message.getFieldWithDefault(msg, 5, 0),
    contentType: jspb.Message.getFieldWithDefault(msg, 6, 0),
    emoticon: (f = msg.getEmoticon()) && proto.bmore.Emoticon.toObject(includeInstance, f),
    tagsList: jspb.Message.getRepeatedField(msg, 8)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bmore.Chat}
 */
proto.bmore.Chat.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bmore.Chat;
  return proto.bmore.Chat.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bmore.Chat} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bmore.Chat}
 */
proto.bmore.Chat.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSender(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReceiver(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCount(value);
      break;
    case 5:
      var value = /** @type {!proto.bmore.Chat.Priority} */ (reader.readEnum());
      msg.setPriority(value);
      break;
    case 6:
      var value = /** @type {!proto.bmore.Chat.ContentType} */ (reader.readEnum());
      msg.setContentType(value);
      break;
    case 7:
      var value = new proto.bmore.Emoticon;
      reader.readMessage(value,proto.bmore.Emoticon.deserializeBinaryFromReader);
      msg.setEmoticon(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bmore.Chat.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bmore.Chat.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bmore.Chat} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bmore.Chat.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSender();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReceiver();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getPriority();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getContentType();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getEmoticon();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.bmore.Emoticon.serializeBinaryToWriter
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.bmore.Chat.Priority = {
  LOW: 0,
  MEDIUM: 1,
  HIGH: 2
};

/**
 * @enum {number}
 */
proto.bmore.Chat.ContentType = {
  TEXT: 0,
  HTML: 1,
  MARKDOWN: 2
};

/**
 * optional string sender = 1;
 * @return {string}
 */
proto.bmore.Chat.prototype.getSender = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.bmore.Chat.prototype.setSender = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string receiver = 2;
 * @return {string}
 */
proto.bmore.Chat.prototype.getReceiver = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.bmore.Chat.prototype.setReceiver = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string text = 3;
 * @return {string}
 */
proto.bmore.Chat.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.bmore.Chat.prototype.setText = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint32 count = 4;
 * @return {number}
 */
proto.bmore.Chat.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.bmore.Chat.prototype.setCount = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional Priority priority = 5;
 * @return {!proto.bmore.Chat.Priority}
 */
proto.bmore.Chat.prototype.getPriority = function() {
  return /** @type {!proto.bmore.Chat.Priority} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.bmore.Chat.Priority} value */
proto.bmore.Chat.prototype.setPriority = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional ContentType content_type = 6;
 * @return {!proto.bmore.Chat.ContentType}
 */
proto.bmore.Chat.prototype.getContentType = function() {
  return /** @type {!proto.bmore.Chat.ContentType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.bmore.Chat.ContentType} value */
proto.bmore.Chat.prototype.setContentType = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional Emoticon emoticon = 7;
 * @return {?proto.bmore.Emoticon}
 */
proto.bmore.Chat.prototype.getEmoticon = function() {
  return /** @type{?proto.bmore.Emoticon} */ (
    jspb.Message.getWrapperField(this, proto.bmore.Emoticon, 7));
};


/** @param {?proto.bmore.Emoticon|undefined} value */
proto.bmore.Chat.prototype.setEmoticon = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.bmore.Chat.prototype.clearEmoticon = function() {
  this.setEmoticon(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.bmore.Chat.prototype.hasEmoticon = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated string tags = 8;
 * @return {!Array.<string>}
 */
proto.bmore.Chat.prototype.getTagsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array.<string>} value */
proto.bmore.Chat.prototype.setTagsList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.bmore.Chat.prototype.addTags = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


proto.bmore.Chat.prototype.clearTagsList = function() {
  this.setTagsList([]);
};


