/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.bmore.Conversation');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.bmore.Chat');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bmore.Conversation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bmore.Conversation.repeatedFields_, null);
};
goog.inherits(proto.bmore.Conversation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bmore.Conversation.displayName = 'proto.bmore.Conversation';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bmore.Conversation.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bmore.Conversation.prototype.toObject = function(opt_includeInstance) {
  return proto.bmore.Conversation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bmore.Conversation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bmore.Conversation.toObject = function(includeInstance, msg) {
  var f, obj = {
    sentAt: jspb.Message.getFieldWithDefault(msg, 1, 0),
    chatsList: jspb.Message.toObjectList(msg.getChatsList(),
    proto.bmore.Chat.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bmore.Conversation}
 */
proto.bmore.Conversation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bmore.Conversation;
  return proto.bmore.Conversation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bmore.Conversation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bmore.Conversation}
 */
proto.bmore.Conversation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSentAt(value);
      break;
    case 2:
      var value = new proto.bmore.Chat;
      reader.readMessage(value,proto.bmore.Chat.deserializeBinaryFromReader);
      msg.addChats(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bmore.Conversation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bmore.Conversation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bmore.Conversation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bmore.Conversation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSentAt();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getChatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.bmore.Chat.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 sent_at = 1;
 * @return {number}
 */
proto.bmore.Conversation.prototype.getSentAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.bmore.Conversation.prototype.setSentAt = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated Chat chats = 2;
 * @return {!Array.<!proto.bmore.Chat>}
 */
proto.bmore.Conversation.prototype.getChatsList = function() {
  return /** @type{!Array.<!proto.bmore.Chat>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bmore.Chat, 2));
};


/** @param {!Array.<!proto.bmore.Chat>} value */
proto.bmore.Conversation.prototype.setChatsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bmore.Chat=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bmore.Chat}
 */
proto.bmore.Conversation.prototype.addChats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bmore.Chat, opt_index);
};


proto.bmore.Conversation.prototype.clearChatsList = function() {
  this.setChatsList([]);
};


